# Generated by Django 3.2.5 on 2021-10-28 02:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='json',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
