# Generated by Django 3.2.4 on 2021-06-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0002_activebounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='bounty',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
