# Generated by Django 3.2.4 on 2021-06-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0004_alter_bounty_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='activebounty',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
