# Generated by Django 3.2.4 on 2021-07-02 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0005_activebounty_started'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveBountySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('photo', models.ImageField(upload_to='bounty_submission')),
            ],
        ),
        migrations.AddField(
            model_name='activebounty',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.activebountysubmission'),
        ),
    ]
