# Generated by Django 3.2.4 on 2021-07-06 10:32

import bounty.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0008_alter_activebountysubmission_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activebountysubmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=bounty.models.nameFile),
        ),
    ]
