# Generated by Django 3.2.4 on 2021-07-09 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0009_alter_activebountysubmission_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activebounty',
            name='submission',
        ),
        migrations.AddField(
            model_name='activebountysubmission',
            name='active',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bounty.activebounty'),
        ),
    ]
