# Generated by Django 3.2.4 on 2021-07-09 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bounty', '0011_alter_activebountysubmission_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activebountysubmission',
            old_name='active',
            new_name='activeBounty',
        ),
    ]
