# Generated by Django 3.2.5 on 2021-08-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wante',
            name='theme',
            field=models.CharField(default='None', max_length=1000),
            preserve_default=False,
        ),
    ]
